[package]
name = "rcore-fs-hostfs"
version = "0.1.0"
authors = ["Runji Wang <wangrunji0408@163.com>"]
edition = "2021"

[dependencies]
rcore-fs = { path = "../rcore-fs", features = ["std"] }
nix = { version = "0.29", features = ["fs"] }
log = "0.4"
